// End-to-end verification: a plan added manually via PATCH /api/leads/[id]
// must render fully on the consent PDF (GET .../consent-pdf), with no spurious
// "N/A" on the plan fields. Exercises the REAL route handlers; only the DB and
// auth helper are mocked. The PDF text is extracted from the generated bytes
// (jsPDF emits uncompressed text streams) to prove what actually renders.
import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/lib/supabase", () => ({
  createServiceClient: vi.fn(),
}));
vi.mock("@/lib/auth/require-agent", () => ({
  requireAuthenticatedAgent: vi.fn(),
}));

import { PATCH } from "../route";
import { GET as CONSENT_PDF } from "../consent-pdf/route";
import { createServiceClient } from "@/lib/supabase";
import { requireAuthenticatedAgent } from "@/lib/auth/require-agent";

const AGENT = { id: "a1", slug: "alice" };

function makeParams(id: string) {
  return { params: Promise.resolve({ id }) };
}

function setAuthOk() {
  (requireAuthenticatedAgent as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({
    agent: AGENT,
    user: { id: "user-1" },
  });
}

// DB mock for the PATCH handler. Captures the row passed to .update() so we can
// assert the stored selected_plan jsonb, then hand it to the PDF handler.
function installPatchDb(existingSelectedPlan: Record<string, unknown> | null) {
  const captured: { update?: Record<string, any> } = {};
  const db = {
    from: vi.fn((table: string) => {
      if (table !== "leads") return {};
      return {
        select: () => ({
          eq: () => ({
            single: async () => ({
              data: { agent_id: AGENT.id, selected_plan: existingSelectedPlan },
              error: null,
            }),
          }),
        }),
        update: (row: Record<string, any>) => {
          captured.update = row;
          return { eq: () => Promise.resolve({ error: null }) };
        },
      };
    }),
  };
  (createServiceClient as unknown as ReturnType<typeof vi.fn>).mockReturnValue(db);
  return captured;
}

// DB mock for the consent-pdf handler. lead.selected_plan holds the jsonb the
// PATCH just produced; no consent row exists (forces the lead.selected_plan
// fallback path, incl. effectiveDate).
function installPdfDb(selectedPlan: Record<string, unknown>) {
  const lead = {
    id: "lead-1",
    agent_id: AGENT.id,
    agent_slug: "alice",
    contact_name: "Maria Lopez",
    first_name: "Maria",
    last_name: "Lopez",
    contact_phone: "2395551234",
    contact_email: "maria@example.com",
    dob: "1985-04-12",
    annual_income: 28000,
    signature_data: "",
    consent_ip: "203.0.113.50",
    consent_timestamp: "2026-04-30T14:00:00Z",
    selected_plan: selectedPlan,
    selected_plan_name: selectedPlan.name ?? null,
    selected_premium: (selectedPlan.afterSubsidy as number) ?? (selectedPlan.premium as number) ?? null,
    created_at: "2026-04-29T12:00:00Z",
  };
  const db = {
    from: vi.fn((table: string) => {
      if (table === "leads") {
        return { select: () => ({ eq: () => ({ single: async () => ({ data: lead, error: null }) }) }) };
      }
      if (table === "agents") {
        return {
          select: () => ({
            eq: () => ({
              single: async () => ({ data: { name: "Alice Agent", npn: "123", agency_name: "Test", phone: "555-0000" }, error: null }),
            }),
          }),
        };
      }
      if (table === "consents") {
        return {
          select: () => ({ eq: () => ({ order: () => ({ limit: () => ({ single: async () => ({ data: null, error: null }) }) }) }) }),
        };
      }
      return {};
    }),
  };
  (createServiceClient as unknown as ReturnType<typeof vi.fn>).mockReturnValue(db);
}

// jsPDF writes left-aligned text as literal `(...) Tj` operators in WinAnsi.
// Decoding the bytes as latin1 makes the ASCII content searchable.
function pdfText(buf: Buffer): string {
  return buf.toString("latin1");
}

async function patchPlan(plan: Record<string, unknown>) {
  const req = { json: async () => ({ plan }) } as any;
  return PATCH(req, makeParams("lead-1"));
}

beforeEach(() => {
  vi.clearAllMocks();
});

describe("manual plan entry -> consent PDF", () => {
  it("renders every manually-added plan field on the consent PDF (no N/A)", async () => {
    setAuthOk();

    // 1. Agent adds a plan manually (lead had no plan before).
    const captured = installPatchDb(null);
    const patchRes = await patchPlan({
      name: "QA Manual Plan PPO",
      issuer: "Florida Blue",
      premium: 450,
      deductible: 3500,
      oopMax: 9100,
      effectiveDate: "2026-07-01",
    });
    expect(patchRes.status).toBe(200);

    // The stored jsonb must carry the exact keys the PDF reads.
    const stored = captured.update!.selected_plan;
    expect(stored).toMatchObject({
      name: "QA Manual Plan PPO",
      issuer: "Florida Blue",
      premium: 450,
      deductible: 3500,
      oopMax: 9100,
      effectiveDate: "2026-07-01",
    });
    expect(captured.update!.selected_plan_name).toBe("QA Manual Plan PPO");
    expect(captured.update!.selected_premium).toBe(450);

    // 2. Generate the consent PDF from that stored plan.
    setAuthOk();
    installPdfDb(stored);
    const pdfRes = await CONSENT_PDF({} as any, makeParams("lead-1"));
    expect(pdfRes.status).toBe(200);
    expect(pdfRes.headers.get("content-type")).toBe("application/pdf");

    const text = pdfText(Buffer.from(await pdfRes.arrayBuffer()));

    // 3. Every plan field renders with its saved value.
    expect(text).toContain("QA Manual Plan PPO");      // Nombre del Plan
    expect(text).toContain("450.00");                  // Prima Mensual
    expect(text).toContain("3,500.00");                // Deducible
    expect(text).toContain("9,100.00");                // Gasto maximo de bolsillo
    // Fecha de Vigencia (jsonb fallback): renders the date the agent picked,
    // not a TZ-shifted day-before. fmtDate renders date-only values in UTC, so
    // this is deterministic regardless of the test runner's timezone.
    expect(text).toContain("1 de julio de 2026");

    // And none of the labels degrade to N/A.
    expect(text).not.toMatch(/Prima Mensual: N\/A/);
    expect(text).not.toMatch(/Deducible: N\/A/);
    expect(text).not.toMatch(/Fecha de Vigencia: N\/A/);
  });

  it("renders a genuine $0 field as $0.00, not N/A", async () => {
    setAuthOk();
    const captured = installPatchDb(null);
    await patchPlan({
      name: "Zero Deductible Plan",
      issuer: "Oscar",
      premium: 0,
      deductible: 0,
      oopMax: 0,
      effectiveDate: "2026-08-01",
    });

    setAuthOk();
    installPdfDb(captured.update!.selected_plan);
    const pdfRes = await CONSENT_PDF({} as any, makeParams("lead-1"));
    const text = pdfText(Buffer.from(await pdfRes.arrayBuffer()));

    expect(text).toContain("$0.00");
    expect(text).not.toMatch(/Deducible: N\/A/);
  });

  it("preserves pre-existing keys (id/metal/afterSubsidy) when editing", async () => {
    setAuthOk();
    const captured = installPatchDb({ id: "12345FL0010001", metal: "gold", afterSubsidy: 80, pcp: 25 });
    await patchPlan({
      name: "Edited Name",
      issuer: "Aetna",
      premium: 500,
      deductible: 2000,
      oopMax: 8000,
      effectiveDate: "2026-09-01",
    });

    const stored = captured.update!.selected_plan;
    expect(stored.id).toBe("12345FL0010001");
    expect(stored.metal).toBe("gold");
    expect(stored.pcp).toBe(25);
    // selected_premium follows afterSubsidy when present (matches plan-select).
    expect(captured.update!.selected_premium).toBe(80);
  });
});
