"use client";
import LegalLayout from "@/components/legal/LegalLayout";

function Section({ id, children }) {
  return <section id={id} className="mb-10 scroll-mt-24">{children}</section>;
}
function H2({ children }) {
  return <h2 className="text-lg font-semibold text-slate-900 mb-3">{children}</h2>;
}
function P({ children }) {
  return <p className="text-sm text-slate-600 leading-relaxed mb-3">{children}</p>;
}
function AlertBox({ type = "info", children }) {
  const styles = {
    info: "border-teal-200 bg-teal-50/50 text-teal-800",
    warning: "border-amber-200 bg-amber-50/50 text-amber-800",
    danger: "border-red-200 bg-red-50/50 text-red-800",
  };
  return (
    <div className={`rounded-xl border p-4 my-4 text-sm leading-relaxed ${styles[type]}`}>
      {children}
    </div>
  );
}
function ListItem({ bold, children }: { bold?: string; children: React.ReactNode }) {
  return (
    <div className="flex gap-2 mb-2 text-sm text-slate-600">
      <span className="text-teal-500 mt-1 flex-shrink-0">•</span>
      <span>{bold && <strong className="text-slate-700">{bold} </strong>}{children}</span>
    </div>
  );
}

const CONTENT = {
  en: [
    {
      id: "critical",
      title: null,
      content: (
        <AlertBox type="danger">
          <div className="flex items-start gap-3">
            <span className="text-lg">🤖</span>
            <div>
              <strong className="block mb-1">Critical Disclaimer</strong>
              The AI Plan Advisor is an experimental educational tool. It is NOT a licensed insurance agent, financial advisor, or healthcare provider. All AI-generated content should be verified with official sources before making any decisions.
            </div>
          </div>
        </AlertBox>
      ),
    },
    {
      id: "nature",
      title: "1. Nature of AI-Generated Content",
      content: (
        <>
          <P>The AI Plan Advisor feature of EnrollSalud uses artificial intelligence technology (powered by Anthropic's Claude API) to provide plain-language explanations of health insurance plans, financial strategies, and year-over-year comparisons.</P>
          <P>All content generated by the AI Plan Advisor:</P>
          <ListItem>Is for educational and informational purposes ONLY</ListItem>
          <ListItem>Does NOT constitute insurance, financial, tax, or medical advice</ListItem>
          <ListItem>May contain errors, inaccuracies, or outdated information</ListItem>
          <ListItem>Should NEVER be the sole basis for enrollment or financial decisions</ListItem>
          <ListItem>Does NOT create any professional-client relationship</ListItem>
        </>
      ),
    },
    {
      id: "limitations",
      title: "2. Limitations of AI Technology",
      content: (
        <>
          <P>Users should be aware that AI technology has inherent limitations:</P>
          <ListItem bold="Accuracy:">The AI may generate incorrect calculations, misinterpret plan details, or provide outdated information. Premium estimates, subsidy calculations, and cost comparisons may not reflect actual amounts.</ListItem>
          <ListItem bold="Personalization:">The AI cannot account for all individual circumstances, including specific medical conditions, provider preferences, prescription needs, or complex tax situations.</ListItem>
          <ListItem bold="Currency:">AI responses are based on training data that may not reflect the most recent plan changes, rate updates, or regulatory modifications.</ListItem>
          <ListItem bold="Bias:">AI systems may reflect biases present in training data and may not provide equally comprehensive information for all plan types or situations.</ListItem>
        </>
      ),
    },
    {
      id: "responsibilities",
      title: "3. User Responsibilities",
      content: (
        <>
          <P>Before making any decisions based on AI Plan Advisor content, users MUST:</P>
          <div className="grid gap-3 my-4">
            {[
              { num: "1", text: "Verify all plan details, premiums, and benefits directly with the insurance carrier or on HealthCare.gov." },
              { num: "2", text: "Consult with a licensed insurance agent for personalized plan recommendations." },
              { num: "3", text: "Speak with a tax professional regarding subsidy eligibility, APTC calculations, and tax implications." },
              { num: "4", text: "Consult a healthcare provider for any medical decisions related to plan selection." },
            ].map((item) => (
              <div key={item.num} className="flex gap-3 items-start p-3 bg-slate-50 rounded-lg border border-slate-100">
                <span className="w-6 h-6 rounded-full bg-teal-100 text-teal-700 flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5">
                  {item.num}
                </span>
                <span className="text-sm text-slate-600">{item.text}</span>
              </div>
            ))}
          </div>
        </>
      ),
    },
    {
      id: "yoy",
      title: "4. Year-Over-Year Comparison Disclaimer",
      content: (
        <>
          <P>The AI Plan Advisor may provide comparisons between plan years (e.g., 2025 vs. 2026 costs). These comparisons are based on publicly available data and general subsidy formulas. Actual costs may vary significantly based on individual circumstances, final rate filings, and federal/state regulatory changes.</P>
          <AlertBox type="warning">
            Premium and subsidy estimates are approximations only. Actual amounts will be determined during the official enrollment process on HealthCare.gov.
          </AlertBox>
        </>
      ),
    },
    {
      id: "no-endorsement",
      title: "5. No Endorsement",
      content: (
        <P>The AI Plan Advisor does not endorse, recommend, or promote any specific health insurance plan, carrier, or provider network. Any mention of specific plans is for informational and comparison purposes only.</P>
      ),
    },
  ],
  es: [
    {
      id: "critical",
      title: null,
      content: (
        <AlertBox type="danger">
          <div className="flex items-start gap-3">
            <span className="text-lg">🤖</span>
            <div>
              <strong className="block mb-1">Aviso Crítico</strong>
              El Asesor de Planes con IA es una herramienta educativa experimental. NO es un agente de seguros licenciado, asesor financiero o proveedor de salud. Todo contenido generado por IA debe verificarse con fuentes oficiales antes de tomar cualquier decisión.
            </div>
          </div>
        </AlertBox>
      ),
    },
    {
      id: "nature",
      title: "1. Naturaleza del Contenido Generado por IA",
      content: (
        <>
          <P>La función de Asesor de Planes con IA de EnrollSalud utiliza tecnología de inteligencia artificial (impulsada por la API Claude de Anthropic) para proporcionar explicaciones en lenguaje sencillo de planes de seguro médico, estrategias financieras y comparaciones año a año.</P>
          <P>Todo contenido generado por el Asesor de Planes con IA:</P>
          <ListItem>Es SOLAMENTE con fines educativos e informativos</ListItem>
          <ListItem>NO constituye asesoría de seguros, financiera, fiscal o médica</ListItem>
          <ListItem>Puede contener errores, inexactitudes o información desactualizada</ListItem>
          <ListItem>NUNCA debe ser la única base para decisiones de inscripción o financieras</ListItem>
          <ListItem>NO crea ninguna relación profesional-cliente</ListItem>
        </>
      ),
    },
    {
      id: "limitations",
      title: "2. Limitaciones de la Tecnología IA",
      content: (
        <>
          <P>Los usuarios deben saber que la tecnología IA tiene limitaciones inherentes:</P>
          <ListItem bold="Precisión:">La IA puede generar cálculos incorrectos, malinterpretar detalles de planes o proporcionar información desactualizada. Las estimaciones de primas, cálculos de subsidios y comparaciones de costos pueden no reflejar montos reales.</ListItem>
          <ListItem bold="Personalización:">La IA no puede considerar todas las circunstancias individuales, incluyendo condiciones médicas específicas, preferencias de proveedores, necesidades de medicamentos o situaciones fiscales complejas.</ListItem>
          <ListItem bold="Actualización:">Las respuestas de la IA se basan en datos de entrenamiento que pueden no reflejar los cambios más recientes en planes, actualizaciones de tarifas o modificaciones regulatorias.</ListItem>
          <ListItem bold="Sesgo:">Los sistemas de IA pueden reflejar sesgos presentes en los datos de entrenamiento y pueden no proporcionar información igualmente completa para todos los tipos de planes.</ListItem>
        </>
      ),
    },
    {
      id: "responsibilities",
      title: "3. Responsabilidades del Usuario",
      content: (
        <>
          <P>Antes de tomar cualquier decisión basada en contenido del Asesor con IA, los usuarios DEBEN:</P>
          <div className="grid gap-3 my-4">
            {[
              { num: "1", text: "Verificar todos los detalles del plan, primas y beneficios directamente con la aseguradora o en CuidadoDeSalud.gov." },
              { num: "2", text: "Consultar con un agente de seguros licenciado para recomendaciones personalizadas de planes." },
              { num: "3", text: "Hablar con un profesional de impuestos sobre elegibilidad de subsidios, cálculos de APTC e implicaciones fiscales." },
              { num: "4", text: "Consultar a un proveedor de salud para cualquier decisión médica relacionada con la selección de plan." },
            ].map((item) => (
              <div key={item.num} className="flex gap-3 items-start p-3 bg-slate-50 rounded-lg border border-slate-100">
                <span className="w-6 h-6 rounded-full bg-teal-100 text-teal-700 flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5">
                  {item.num}
                </span>
                <span className="text-sm text-slate-600">{item.text}</span>
              </div>
            ))}
          </div>
        </>
      ),
    },
    {
      id: "yoy",
      title: "4. Aviso de Comparación Año a Año",
      content: (
        <>
          <P>El Asesor de Planes con IA puede proporcionar comparaciones entre años de plan (ej. costos 2025 vs. 2026). Estas comparaciones se basan en datos públicamente disponibles y fórmulas generales de subsidios. Los costos reales pueden variar significativamente según circunstancias individuales, presentaciones de tarifas finales y cambios regulatorios.</P>
          <AlertBox type="warning">
            Las estimaciones de primas y subsidios son solo aproximaciones. Los montos reales se determinarán durante el proceso de inscripción oficial en CuidadoDeSalud.gov.
          </AlertBox>
        </>
      ),
    },
    {
      id: "no-endorsement",
      title: "5. Sin Endorso",
      content: (
        <P>El Asesor de Planes con IA no respalda, recomienda ni promueve ningún plan de seguro médico, aseguradora o red de proveedores específica. Cualquier mención de planes específicos es solo con fines informativos y de comparación.</P>
      ),
    },
  ],
};

export default function AIDisclaimerPage() {
  return (
    <LegalLayout titleEn="AI Plan Advisor Disclaimer" titleEs="Aviso Legal del Asesor de Planes con IA">
      {(lang) => (
        <div>
          {CONTENT[lang].map((section) => (
            <Section key={section.id} id={section.id}>
              {section.title && <H2>{section.title}</H2>}
              {section.content}
            </Section>
          ))}
        </div>
      )}
    </LegalLayout>
  );
}
